### ISSUE TITLE
New room in practice range does not show up 

### ISSUE THREAD

**Issue by KripC2160** [luvyana/val-scripts#1]
There is a new room in practice range and when I tried using the script, only the lights seems to be imported. 
![image](https://user-images.githubusercontent.com/65854891/141744397-59b46cbf-4ef0-4bfd-9e06-d1762c24b1ad.png)

**Comment by floxay** [comment]
You have to manually add the new .umap file(s) for that room in the list at [_umapList.py#L164](https://github.com/luvyana/val-scripts/blob/main/utils/_umapList.py#L164)

**Comment by KripC2160** [comment]
cool thanks
